[project]
name = "pixel-labler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-genai>=1.56.0",
    "opencv-python>=4.12.0.88",
    "pillow>=12.0.0",
]
